#!/bin/bash

set -e

echo "install"

main(){
    case "$(uname -s)" in
        Darwin)
            xcode-select --install || true # errors if already installed
            brew bundle
            bash install-npm-global-packages
            ;;
    esac
    ./bin/caps-to-control
}

main

