#!/bin/bash

alias s='source ~/.zshrc'

# vim
# use brew vim over system vim
alias vim='/opt/homebrew/bin/vim'
alias vi='vim'
alias v='vim'

# git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gp='git push'
alias gl='git pull'
alias gd='git diff --word-diff=color'
alias gdca='git diff --cached'
alias gco='git checkout'
alias gc='git commit'
alias glog='git log'
alias gb='git branch'

# docker 
alias d='docker'
alias di='docker images'
alias dps='docker ps'
alias db='docker build'
alias dr='docker run'
alias de='docker exec'
alias drm='docker rm'
alias drmi='docker rmi'

# chrome
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

# ls
alias l='ls -laG'

# dir movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias o="open"

alias serverless="nocorrect serverless"

alias tf2="terraform12"
alias tf="terraform"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfd="terraform destroy"
alias tf0="terraform output"

alias npx="nocorrect npx"

alias c="pbcopy"
alias p="pbpaste"

alias python="python3"
alias pip="pip3"
