#!/bin/bash

# tmux
tmux_list_sessions(){
    tmux list-sessions | cut -d ":" -f1
}

tmux_get_session_from_ls(){
    local session_num
    session_num=$1
    tmux_list_sessions | sed -n "$session_num"p
}

tmux_go_to_session_num() {
    local session_num
    local session_name
    session_num=$1
    session_name=$(tmux_get_session_from_ls "$session_num");
    if [ -n "$TMUX" ]; 
    then 
        tmux switch -t "$session_name";
    else
        tmux attach -t "$session_name"
    fi; 
}

#sketch. Create a timestamp_name folder in ~/Temp
sketch(){
    local sketch_name
    local dir_name
    local tmp_dir
    if [ $# -eq 1 ]
    then
        sketch_name=_$1
    fi
    dir_name="$(date +"%Y-%m-%d_%H.%M.%S")$sketch_name" 

    tmp_dir=~/Tmp/"$dir_name"
    mkdir "$tmp_dir" && cd "$tmp_dir" && pwd
}

take(){
    local dir_name
    dir_name=$1
    mkdir -p "$dir_name" && cd "$dir_name" || exit
}

resn_clone(){
    local repo_name
    repo_name=$1
    git clone jesusgollonet@bitbucket.org:resn/"$repo_name".git
}
