#!/bin/zsh

bindkey '^R' history-incremental-search-backward
#http://floatleft.com/notebook/mac-like-text-navigation-in-zsh
# Skip forward/back a word with opt-arrow
bindkey '[C' forward-word
bindkey '[D' backward-word

# Skip to start/end of line with cmd-arrow
bindkey '[E' beginning-of-line
bindkey '[F' end-of-line

# Delete word with opt-backspace/opt-delete
bindkey '[G' backward-kill-word
bindkey '[H' kill-word

# Delete line with cmd-backspace
bindkey '[I' kill-whole-line

# search history with up & down
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# F1 to F5 go to tmux sessions 
bindkey -s  '^[OP' 'tmux_go_to_session_num 1\n'
bindkey -s  '^[OQ' 'tmux_go_to_session_num 2\n'
bindkey -s  '^[OR' 'tmux_go_to_session_num 3\n'
bindkey -s  '^[OS' 'tmux_go_to_session_num 4\n'
bindkey -s  '^[[15~' 'tmux_go_to_session_num 5\n'

# both ⏪ F7 and ⏩ F9 attach to tmux session (cycle through behaviour)
bindkey -s '^[[18~' 'tmux attach\n'
bindkey -s '^[[20~' 'tmux attach\n'
# F8 ⏯  lists current tmux sessions  
bindkey -s '^[[19~' 'tmux ls\n'
# F12 sends process to foreground (mostly for vim)
bindkey -s '^[[24~' 'open_or_foreground_vim\n'
#bindkey '^[[24~' open_or_foreground_vim
