#!/bin/zsh

autoload -Uz promptinit
promptinit

autoload -Uz compinit
compinit

prompt off

# history search with arrows 
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# # Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

. ~/.dotfiles/zsh/keys
. ~/.dotfiles/zsh/aliases
. ~/.dotfiles/zsh/functions
. ~/.dotfiles/zsh/setopt
. ~/.dotfiles/tmux/aliases
. ~/.bin/z.sh

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.history



# add bin to path
export PATH=~/.bin:$PATH
export PATH=~/.dotfiles/bin:$PATH

source ~/.dotfiles/zsh/lib/zsh-git-prompt/zshrc.sh
# an example prompt
PROMPT='%B%m%~%b$(git_super_status) %# '
# enable fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# source google cloud sdk files
[ -f ~/.google-cloud-sdk/completion.zsh.inc ] && source ~/.google-cloud-sdk/completion.zsh.inc
[ -f ~/.google-cloud-sdk/path.zsh.inc ] && source ~/.google-cloud-sdk/path.zsh.inc
# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='find .'
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# load z
